apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pyscaler-deployment 
  labels:
    app: pyscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyscaler
  template:
    metadata:
      labels:
        app: pyscaler
    spec:
      containers:
      - name: pyscaler
        image: memcached-pyscaler:v1
        ports:
        - containerPort: 5000
        env:
        - name: MEMCACHED_HOST
          value: "memcached-service"
        - name: MEMCACHED_PORT
          value: "11211"
