apiVersion: autoscaling/v2alpha1
kind: HorizontalPodAutoscaler
metadata:
  name: memcached-hpa  
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: memcached-deployment
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: pyscaler-service
      metricName: "99th_percentile"
      targetValue: 2
