apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: influxdb
  ports:
  - name: admin-console
    protocol: TCP
    port: 8083
    targetPort: 8083
  - name: data-api
    protocol: TCP
    port: 8086
    targetPort: 8086
  type: NodePort
