apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: memcached-metrics-deployment 
  labels:
    app: memcached-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached-metrics
  template:
    metadata:
      labels:
        app: memcached-metrics
    spec:
      containers:
      - name: memcached-metrics
        image: memcached-metrics:v1
        env:
        - name: MCROUTER_HOST
          value: "mcrouter-service"
        - name: MCROUTER_PORT
          value: "5000"
        - name: INFLUXDB_HOST
          value: "influxdb-service"
        - name: INFLUXDB_PORT
          value: "8086"
        - name: INFLUXDB_DBNAME
          value: "metrics"
