apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: memcached-metrics-deployment 
  labels:
    app: memcached-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached-metrics
  template:
    metadata:
      labels:
        app: memcached-metrics
    spec:
      containers:
      - name: memcached-metrics
        image: memcached-metrics:v1
        ports:
        - containerPort: 5000
        env:
        - name: MEMCACHED_HOST
          value: "memcached-service"
        - name: MEMCACHED_PORT
          value: "11211"
